Repository AT-PHPIntership/foody, pull requests merged in 2018-08, with the labels that each got.

#9 create new user
  app/Http/Controllers/Admin/UserController.php
  app/Http/Requests/CreateUserRequest.php
  database/migrations/2018_07_23_072844_create_users_table.php
  resources/lang/en/user.php
  resources/views/admin/includes/message.blade.php
  resources/views/admin/pages/users/create.blade.php
  resources/views/admin/pages/users/index.blade.php
  tests/Browser/Admin/AdminTestCase.php
  tests/Browser/Admin/Users/CreateUserTest.php
  tests/Browser/Admin/Users/ShowListUserTest.php
  tests/Browser/Pages/Admin/User/CreateUser.php
Labels: in progress

#10 Create category
  .bowerrc
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/Admin/CreateCategoryRequest.php
  config/paginate.php
  database/seeds/CategoriesTableSeeder.php
  resources/views/admin/includes/footer.blade.php
  resources/views/admin/includes/head.blade.php
  resources/views/admin/includes/left-bar.blade.php
  resources/views/admin/pages/categories/create.blade.php
  resources/views/admin/pages/categories/index.blade.php
  resources/views/admin/pages/categories/showChild.blade.php
  tests/Browser/Admin/AdminTestCase.php
  tests/Browser/Admin/Categories/CreateCategoryTest.php
  tests/Browser/Pages/Admin/Category/CreateCategory.php
Labels: in progress

#11 Delete category
  app/Http/Controllers/Admin/CategoryController.php
  resources/views/admin/includes/footer.blade.php
  resources/views/admin/pages/categories/index.blade.php
  tests/Browser/Admin/Auth/LoginTest.php
  tests/Browser/Admin/Categories/CreateCategoryTest.php
  tests/Browser/Admin/Categories/DeleteCategoryTest.php
  tests/Browser/Admin/Categories/ListCategoriesTest.php
Labels: in progress

#12 Delete user
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/includes/message.blade.php
  resources/views/admin/pages/users/index.blade.php
  tests/Browser/Admin/Users/DeleteUserTest.php
Labels: in progress

#13 Edit category
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/Admin/EditCategoryRequest.php
  app/Models/Category.php
  resources/views/admin/pages/categories/edit.blade.php
  resources/views/admin/pages/categories/index.blade.php
  resources/views/admin/pages/categories/showChild.blade.php
  tests/Browser/Admin/Categories/ListCategoriesTest.php
  tests/Browser/Admin/Categories/UpdateCategoryTest.php
  tests/Browser/Pages/Admin/Category/UpdateCategory.php
  tests/Browser/Pages/Admin/Category/UpdateChildCategory.php
Labels: in progress

#14 Update user
  app/Http/Controllers/Admin/UserController.php
  app/Http/Requests/UpdateUserRequest.php
  resources/lang/en/user.php
  resources/views/admin/pages/users/edit.blade.php
  tests/Browser/Admin/Users/UpdateUserTest.php
  tests/Browser/Pages/Admin/User/UpdateUser.php
Labels: in progress

#16 show list products
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Admin/UserController.php
  app/Models/Product.php
  app/Models/User.php
  composer.json
  composer.lock
  config/app.php
  config/columnsortable.php
  config/paginate.php
  database/seeds/ProductsTableSeeder.php
  public/images/products/no-image.jpg
  resources/lang/en/product.php
  resources/views/admin/includes/left-bar.blade.php
  resources/views/admin/pages/products/index.blade.php
  resources/views/admin/pages/products/show.blade.php
  resources/views/admin/pages/users/index.blade.php
  routes/web.php
  tests/Browser/Admin/Users/ShowListUserTest.php
  tests/Browser/Pages/Admin/Product/ShowProduct.php
Labels: in progress

#17 Delete store, fix delete child category
  .gitignore
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Controllers/Admin/StoreController.php
  resources/lang/en/category.php
  resources/views/admin/pages/categories/index.blade.php
  resources/views/admin/pages/categories/showChild.blade.php
  tests/Browser/Admin/Stores/DeleteStoreTest.php
  tests/Browser/Pages/Admin/Store/ListStores.php
Labels: in progress

#18 Create store
  app/Http/Controllers/Admin/StoreController.php
  app/Http/Requests/Admin/CreateStoreRequest.php
  app/Models/Store.php
  config/define.php
  database/migrations/2018_07_23_072847_create_stores_table.php
  resources/lang/en/store.php
  resources/views/admin/includes/head.blade.php
  resources/views/admin/includes/left-bar.blade.php
  resources/views/admin/pages/stores/create.blade.php
  resources/views/admin/pages/stores/index.blade.php
  resources/views/admin/pages/stores/show.blade.php
Labels: in progress

#19 Edit store
  app/Http/Controllers/Admin/StoreController.php
  app/Http/Requests/Admin/UpdateStoreRequest.php
  resources/lang/en/store.php
  resources/views/admin/pages/stores/edit.blade.php
Labels: in progress

#21 Show list orders
  app/Http/Controllers/Admin/OrderController.php
  app/Models/Order.php
  config/paginate.php
  database/seeds/OrderDetailsTableSeeder.php
  database/seeds/OrdersTableSeeder.php
  resources/lang/en/order.php
  resources/views/admin/includes/left-bar.blade.php
  resources/views/admin/pages/orders/index.blade.php
  routes/web.php
Labels: in progress

#22 Delete orders
  app/Http/Controllers/Admin/OrderController.php
  database/seeds/DatabaseSeeder.php
  database/seeds/OrderDetailsTableSeeder.php
Labels: in progress

#20 Create product
  .gitignore
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/CreateProductRequest.php
  config/define.php
  resources/lang/en/product.php
  resources/views/admin/pages/products/create.blade.php
  resources/views/admin/pages/products/index.blade.php
  resources/views/admin/pages/products/show.blade.php
  resources/views/admin/pages/users/create.blade.php
  tests/Browser/Admin/Products/CreateProductTest.php
  tests/Browser/Admin/Products/test/image1.jpg
  tests/Browser/Pages/Admin/Product/CreateProduct.php
  tests/Browser/Pages/Admin/Store/ListStores.php
Labels: in progress

#23 Update product
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/UpdateProductRequest.php
  database/seeds/ImagesTableSeeder.php
  resources/lang/en/product.php
  resources/lang/en/user.php
  resources/views/admin/pages/products/edit.blade.php
  resources/views/admin/pages/products/index.blade.php
  resources/views/admin/pages/products/show.blade.php
  resources/views/admin/pages/users/edit.blade.php
  tests/Browser/Admin/Products/UpdateProductTest.php
  tests/Browser/Admin/Users/CreateUserTest.php
  tests/Browser/Admin/Users/UpdateUserTest.php
  tests/Browser/Pages/Admin/Product/UpdateProduct.php
  tests/Browser/Pages/Admin/User/UpdateUser.php
Labels: in progress

#25 Show detail order, update status order
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Requests/Admin/EditStatusOrderRequest.php
  app/Models/Order.php
  database/factories/OrderFactory.php
  database/migrations/2018_07_23_072845_create_orders_table.php
  resources/lang/en/detail_order.php
  resources/lang/en/order.php
  resources/views/admin/pages/orders/index.blade.php
  resources/views/admin/pages/orders/show.blade.php
Labels: in progress

#27 Fix sort list and fix add edit
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Controllers/Admin/OrderController.php
  app/Models/Category.php
  app/Models/Order.php
  app/Models/Store.php
  resources/views/admin/pages/categories/create.blade.php
  resources/views/admin/pages/categories/edit.blade.php
  resources/views/admin/pages/categories/index.blade.php
  resources/views/admin/pages/categories/showChild.blade.php
  resources/views/admin/pages/orders/index.blade.php
  resources/views/admin/pages/stores/create.blade.php
  resources/views/admin/pages/stores/edit.blade.php
  resources/views/admin/pages/stores/index.blade.php
Labels: in progress

#29 Api user category
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/Api/User/CategoryController.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  app/Traits/ApiResponser.php
  composer.json
  composer.lock
  config/auth.php
  config/database.php
  database/seeds/CategoriesTableSeeder.php
  database/seeds/ShopOpeningStatusesTableSeeder.php
  docs/api-references/category.md
  phpunit.xml
  public/js/public/category.js
  public/user/Content/site.css
  public/user/Files/admin/08082018/avt-ga-hap-nuoc-mam.png
  public/user/Files/admin/23042018/avt-ca-loc-quay-me.png
  public/user/Files/admin/23042018/ga-bo-xoi-sot-tieu-xanh-flyfood.jpg
  public/user/Files/admin/29062018/avt-gbx3mau.jpg
  resources/views/public/includes/header.blade.php
  resources/views/public/pages/index.blade.php
  routes/api.php
  tests/Feature/Api/ShowCategoriesMenuTest.php
  tests/Feature/ExampleTest.php
  tests/Unit/ExampleTest.php
Labels: User, in progress

#30 Api Register user
  app/Http/Controllers/Api/User/LoginController.php
  app/Http/Requests/User/ApiFormRequest.php
  app/Http/Requests/User/RegisterRequest.php
  database/factories/UserFactory.php
  public/js/public/register.js
  public/user/Files/admin/08082018/avt-ga-hap-nuoc-mam.png
  resources/lang/en/user/register.php
  resources/views/public/includes/footer.blade.php
  resources/views/public/includes/head.blade.php
  routes/api.php
Labels: User, in progress

#31 Register use doc test
  docs/api-references/user.md
  tests/Feature/Api/RegisterTest.php
  tests/TestCase.php
Labels: User, in progress

#33 Api Login/Logout user
  app/Http/Controllers/Api/User/LoginController.php
  app/Models/User.php
  config/app.php
  config/define.php
  public/js/public/login.js
  public/js/public/logout.js
  public/user/Content/site.css
  public/user/Files/admin/08082018/avt-ga-hap-nuoc-mam.png
  resources/lang/en/user/login.php
  resources/views/public/includes/footer.blade.php
  resources/views/public/includes/header.blade.php
  routes/api.php
Labels: User, in progress

#34 Login logout user doc test
  docs/api-references/user.md
  tests/Feature/Api/LoginTest.php
  tests/TestCase.php
Labels: User

#32 Api show newest products slide
  app/Http/Controllers/Api/User/ProductController.php
  app/Models/Product.php
  app/Traits/FilterTrait.php
  public/js/public/index.js
  public/user/Content/site.css
  resources/views/public/pages/index.blade.php
  routes/api.php
Labels: User, in progress

#35 Doc test show newest products slide
  docs/api-references/product.md
  tests/Feature/Api/ShowNewestProductsSlideTest.php
Labels: User

#36 Show products in category home page
  app/Http/Controllers/Api/User/ProductController.php
  app/Traits/FilterTrait.php
  config/define.php
  docs/api-references/product.md
  public/js/public/index.js
  resources/views/public/pages/index.blade.php
Labels: User

#37 Update user info
  app/Http/Controllers/Api/User/UserController.php
  app/Http/Controllers/Api/User/UserInfoController.php
  app/Http/Controllers/Home/UserController.php
  app/Http/Requests/UpdateUserRequest.php
  config/localization-js.php
  public/assets/dist/lang.dist.js
  public/js/messages.js
  public/js/public/login.js
  public/js/public/userInfo.js
  resources/lang/en/user/login.php
  resources/views/public/includes/footer.blade.php
  resources/views/public/includes/header.blade.php
  resources/views/public/pages/userInfo.blade.php
  routes/api.php
  routes/web.php
Labels: User

#38 Show category products page
  app/Http/Controllers/Api/User/ProductController.php
  app/Http/Controllers/Home/ProductController.php
  app/Traits/FilterTrait.php
  config/define.php
  public/js/public/index.js
  public/js/public/main.js
  public/js/public/product.js
  public/js/public/route.js
  public/user/Content/site.css
  resources/views/public/includes/footer.blade.php
  resources/views/public/pages/category.blade.php
  resources/views/public/pages/product.blade.php
  resources/views/public/pages/products.blade.php
  routes/web.php
Labels: User

#39 [User login] Create check log in token function to check user logged in or not
  app/Http/Controllers/Api/User/LoginController.php
  public/js/public/login.js
  public/user/Scripts/_references.js
  resources/views/public/includes/footer.blade.php
  resources/views/public/includes/header.blade.php
  routes/api.php
  tests/Feature/Api/LoginTest.php
Labels: User

#40 Update user info doc test
  docs/api-references/userInfo.md
  tests/Feature/Api/UpdateUserInfoTest.php
Labels: User

#41 Add to cart
  public/js/messages.js
  public/js/public/cart.js
  public/js/public/index.js
  public/js/public/main.js
  public/user/Content/site.css
  public/user/Scripts/_references.js
  resources/lang/en/user/index.php
  resources/views/public/includes/footer.blade.php
  resources/views/public/includes/header.blade.php
  resources/views/public/pages/index.blade.php
Labels: User

#42 Show product details
  app/Http/Controllers/Api/User/ProductController.php
  app/Http/Controllers/Home/ProductController.php
  public/js/public/detailsProduct.js
  public/js/public/index.js
  public/js/public/route.js
  public/user/Scripts/_references.js
  resources/lang/en/user/product.php
  resources/views/public/includes/footer.blade.php
  resources/views/public/includes/head.blade.php
  resources/views/public/pages/detailsProduct.blade.php
  resources/views/public/pages/index.blade.php
  routes/web.php
Labels: User

#43 Checkout before confirm order
  app/Http/Controllers/Home/CartController.php
  public/js/messages.js
  public/js/public/cart.js
  public/js/public/checkout.js
  public/js/public/login.js
  public/js/public/main.js
  public/js/public/userInfo.js
  public/messages.js
  public/user/Content/site.css
  public/user/Files/images/top-hover.png
  public/user/Files/images/top.png
  public/user/Scripts/_references.js
  resources/lang/en/user/cart.php
  resources/lang/en/user/login.php
  resources/views/public/includes/footer.blade.php
  resources/views/public/pages/cart.blade.php
  routes/web.php
Labels: User
